# Generated by Django 3.0.2 on 2020-01-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(blank=True, max_length=512, null=True)),
                ('movie_genre', models.CharField(blank=True, choices=[('Action', 'action'), ('Adventure', 'adventure'), ('Comedy', 'comedy'), ('Romantic', 'Romantice')], max_length=32, null=True)),
                ('movie_year', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='accounts.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('voting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voting_type', models.CharField(blank=True, choices=[('Downvote', 'downvote'), ('Upvote', 'upvote')], max_length=32, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting_movie', to='movies_info.Movies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting_user', to='accounts.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_text', models.CharField(blank=True, max_length=512, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_movie', to='movies_info.Movies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='accounts.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_movie', to='movies_info.Movies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='accounts.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('favourite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, choices=[('Action', 'action'), ('Adventure', 'adventure'), ('Comedy', 'comedy'), ('Romantic', 'Romantice')], max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_genre', to='accounts.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
