# Generated by Django 3.0.2 on 2020-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_percentage',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
