# Generated by Django 3.0.2 on 2020-01-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_info', '0002_auto_20200128_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='totalRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
