# Generated by Django 3.0.2 on 2020-01-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_info', '0003_movies_totalrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='totalRating',
        ),
        migrations.AddField(
            model_name='movies',
            name='overallrating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
